AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.7
      CodeUri: ./myfunction/dist

# CONS:
#   - local source only by 'AWS::Serverless::Function'
#   - use 'aws cloudformation package' to upload code after build
